apiVersion: v1
kind: Service
metadata:
  labels:
    app: nnotifications
  name: nnotifications
spec:
  ports:
  - name: "tcp"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nnotifications
  type: ClusterIP