apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: us-east4-docker.pkg.dev/nestjsmicro-433113/auth/production
          env:
            - name: JWT_SECRET
              value: default_jwt_secret
            - name: JWT_EXPIRATION
              value: '3600'
            - name: TCP_PORT
              value: '3002'
            - name: HTTP_PORT
              value: '3003'
            - name: NOTIFICATIONS_HOST
              value: notifications
            - name: NOTIFICATIONS_PORT
              value: '3000'
            - name: MONGODB_URI
              value: mongodb+srv://fazilbgsbu2016:yzKUP4mu7N9RNO8D@cluster0.b9k8q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
              # valueFrom:
              #   secretKeyRef:
              #     name: mongodb
              #     key: connectionString
          ports:
            - containerPort: 3002
            - containerPort: 3003
